import "./functions";
import "./button";
import "./constants";
import "./exercises";
import "./settings";

const deleteF = [
  {
    program: "Strength Squat",
    data: [
      {
        id: 27,
        Date: "8/6/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 120,
        "Static lunge": 60,
        "Barbell row": 65,
        "Barbell press": 90,
        Running: 5,
      },
      {
        id: 26,
        Date: "7/30/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 120,
        "Static lunge": 60,
        "Barbell row": 65,
        "Barbell press": 85,
        Running: 5,
      },
      {
        id: 25,
        Date: "7/22/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 120,
        "Static lunge": 60,
        "Barbell row": 65,
        "Barbell press": 85,
        Running: 5,
      },
      {
        id: 24,
        Date: "7/17/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 120,
        "Static lunge": 60,
        "Barbell row": 65,
        "Barbell press": 85,
        Running: 5,
      },
      {
        id: 23,
        Date: "7/8/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 120,
        "Static lunge": 60,
        "Barbell row": 65,
        "Barbell press": 85,
        Running: 5,
      },
      {
        id: 22,
        Date: "7/2/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 110,
        "Static lunge": 60,
        "Barbell row": 60,
        "Barbell press": 75,
        Running: 5,
      },
      {
        id: 21,
        Date: "6/14/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 120,
        "Static lunge": 60,
        "Barbell row": 60,
        "Barbell press": 82,
        Running: 5,
      },
      {
        id: 20,
        Date: "6/6/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 120,
        "Static lunge": 60,
        "Barbell row": 60,
        "Barbell press": 82,
        Running: 5,
      },
      {
        id: 19,
        Date: "5/28/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 120,
        "Static lunge": 60,
        "Barbell row": 60,
        "Barbell press": 82,
        Running: 5,
      },
      {
        id: 18,
        Date: "5/20/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 115,
        "Static lunge": 50,
        "Barbell row": 65,
        "Barbell press": 80,
        Running: 5,
      },
      {
        id: 17,
        Date: "5/9/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 115,
        "Static lunge": 50,
        "Barbell row": 65,
        "Barbell press": 80,
        Running: 5,
      },
      {
        id: 16,
        Date: "5/9/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 115,
        "Static lunge": 50,
        "Barbell row": 65,
        "Barbell press": 80,
        Running: 5,
      },
      {
        id: 15,
        Date: "4/30/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 115,
        "Static lunge": 50,
        "Barbell row": 65,
        "Barbell press": 80,
        Running: 5,
      },
      {
        id: 14,
        Date: "4/23/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 115,
        "Static lunge": 50,
        "Barbell row": 65,
        "Barbell press": 80,
        Running: 5,
      },
      {
        id: 13,
        Date: "4/18/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 115,
        "Static lunge": 50,
        "Barbell row": 65,
        "Barbell press": 80,
        Running: 5,
      },
      {
        id: 12,
        Date: "4/11/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 110,
        "Static lunge": 50,
        "Barbell row": 60,
        "Barbell press": 80,
        Running: 5,
      },
      {
        id: 11,
        Date: "4/5/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 110,
        "Static lunge": 50,
        "Barbell row": 60,
        "Barbell press": 80,
        Running: 5,
      },
      {
        id: 10,
        Date: "3/26/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Squat: 110,
        "Static lunge": 50,
        "Barbell row": 60,
        "Barbell press": 80,
        Running: 5,
      },
      {
        id: 9,
        Date: "3/22/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 100,
        "Static lunge": 50,
        "Barbell row": 60,
        "Barbell press": 70,
        Running: 5,
      },
      {
        id: 8,
        Date: "3/14/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 90,
        "Static lunge": 50,
        "Barbell row": 60,
        "Barbell press": 70,
        Running: 5,
      },
      {
        id: 7,
        Date: "1/12/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 80,
        "Static lunge": 50,
        "Barbell row": 60,
        "Barbell press": 60,
        Running: 5,
      },
      {
        id: 6,
        Date: "12/18/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 80,
        "Static lunge": 40,
        "Barbell row": 60,
        "Barbell press": 60,
        Running: 5,
      },
      {
        id: 5,
        Date: "10/24/2023",
        Reps: "3x5",
        "Rest (sec)": 120,
        Squat: 120,
        "Static lunge": 50,
        "Barbell row": 70,
        "Barbell press": 80,
        Running: 10,
      },
      {
        id: 4,
        Date: "10/13/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 110,
        "Static lunge": 50,
        "Barbell row": 70,
        "Barbell press": 75,
        Running: 8,
      },
      {
        id: 3,
        Date: "10/4/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 100,
        "Static lunge": 50,
        "Barbell row": 60,
        "Barbell press": 70,
        Running: 3,
      },
      {
        id: 2,
        Date: "9/25/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 90,
        "Static lunge": 45,
        "Barbell row": 70,
        "Barbell press": 70,
        Running: 8,
      },
      {
        id: 1,
        Date: "9/19/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 80,
        "Static lunge": 40,
        "Barbell row": 70,
        "Barbell press": 70,
        Running: 8,
      },
    ],
  },
  {
    program: "Strength Deadlift",
    data: [
      {
        id: 21,
        Date: "8/2/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 125,
        "Dynamic lunge": 50,
        "Shoulder press": 50,
        Pulldowns: 77,
        Running: 7,
      },
      {
        id: 20,
        Date: "7/26/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 125,
        "Dynamic lunge": 50,
        "Shoulder press": 50,
        Pulldowns: 77,
        Running: 7,
      },
      {
        id: 19,
        Date: "7/19/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 125,
        "Dynamic lunge": 50,
        "Shoulder press": 50,
        Pulldowns: 77,
        Running: 7,
      },
      {
        id: 18,
        Date: "7/12/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 120,
        "Dynamic lunge": 50,
        "Shoulder press": 50,
        Pulldowns: 77,
        Running: 7,
      },
      {
        id: 17,
        Date: "7/5/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 110,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 77,
        Running: 7,
      },
      {
        id: 16,
        Date: "6/17/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 120,
        "Dynamic lunge": 50,
        "Shoulder press": 50,
        Pulldowns: 77,
        Running: 7,
      },
      {
        id: 15,
        Date: "6/11/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 120,
        "Dynamic lunge": 50,
        "Shoulder press": 50,
        Pulldowns: 75,
        Running: 7,
      },
      {
        id: 14,
        Date: "5/31/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 120,
        "Dynamic lunge": 47,
        "Shoulder press": 47,
        Pulldowns: 75,
        Running: 7,
      },
      {
        id: 13,
        Date: "5/22/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 120,
        "Dynamic lunge": 47,
        "Shoulder press": 47,
        Pulldowns: 75,
        Running: 7,
      },
      {
        id: 12,
        Date: "5/17/2024",
        Reps: "3x3",
        "Rest (sec)": 120,
        Deadlift: 125,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 75,
        Running: 7,
      },
      {
        id: 11,
        Date: "5/2/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 120,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 70,
        Running: 7,
      },
      {
        id: 10,
        Date: "4/26/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 120,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 70,
        Running: 7,
      },
      {
        id: 9,
        Date: "4/16/2024",
        Reps: "2x5",
        "Rest (sec)": 120,
        Deadlift: 120,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 70,
        Running: 7,
      },
      {
        id: 8,
        Date: "4/2/2024",
        Reps: "3x5",
        "Rest (sec)": 120,
        Deadlift: 120,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 70,
        Running: 7,
      },
      {
        id: 7,
        Date: "3/20/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 110,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 65,
        Running: 7,
      },
      {
        id: 6,
        Date: "3/11/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 110,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 60,
        Running: 7,
      },
      {
        id: 5,
        Date: "12/22/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 50,
        "Shoulder press": 45,
        Pulldowns: 50,
        Running: 9,
      },
      {
        id: 4,
        Date: "10/17/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 110,
        "Dynamic lunge": 60,
        "Shoulder press": 45,
        Pulldowns: 80,
        Running: 9,
      },
      {
        id: 3,
        Date: "10/9/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 110,
        "Dynamic lunge": 60,
        "Shoulder press": 45,
        Pulldowns: 70,
        Running: 8,
      },
      {
        id: 2,
        Date: "9/29/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 100,
        "Dynamic lunge": 60,
        "Shoulder press": 40,
        Pulldowns: 70,
        Running: 3,
      },
      {
        id: 1,
        Date: "9/22/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 60,
        "Shoulder press": 45,
        Pulldowns: 65,
        Running: 8,
      },
    ],
  },
  {
    program: "Break-In Squat",
    data: [
      {
        id: 16,
        Date: "3/6/2024",
        Reps: "3x8",
        "Rest (sec)": 60,
        Squat: 90,
        "Static lunge": 50,
        "Dumbbell row": 60,
        "Barbell press": 70,
        Running: 6,
      },
      {
        id: 15,
        Date: "3/1/2024",
        Reps: "3x8",
        "Rest (sec)": 60,
        Squat: 90,
        "Static lunge": 40,
        "Dumbbell row": 65,
        "Barbell press": 65,
        Running: 6,
      },
      {
        id: 14,
        Date: "1/31/2024",
        Reps: "3x8",
        "Rest (sec)": 60,
        Squat: 90,
        "Static lunge": 50,
        "Dumbbell row": 65,
        "Barbell press": 65,
        Running: 6,
      },
      {
        id: 13,
        Date: "1/24/2024",
        Reps: "3x8",
        "Rest (sec)": 60,
        Squat: 90,
        "Static lunge": 50,
        "Dumbbell row": 65,
        "Barbell press": 65,
        Running: 6,
      },
      {
        id: 12,
        Date: "1/17/2024",
        Reps: "3x8",
        "Rest (sec)": 60,
        Squat: 90,
        "Static lunge": 50,
        "Dumbbell row": 60,
        "Barbell press": 60,
        Running: 5,
      },
      {
        id: 11,
        Date: "1/8/2024",
        Reps: "3x8",
        "Rest (sec)": 60,
        Squat: 80,
        "Static lunge": 50,
        "Dumbbell row": 60,
        "Barbell press": 60,
        Running: 5,
      },
      {
        id: 10,
        Date: "11/24/2023",
        Reps: "3x8",
        "Rest (sec)": 60,
        Squat: 90,
        "Static lunge": 50,
        "Dumbbell row": 60,
        "Barbell press": 60,
        Running: 5,
      },
      {
        id: 9,
        Date: "11/15/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 90,
        "Static lunge": 50,
        "Dumbbell row": 50,
        "Barbell press": 60,
        Running: 5,
      },
      {
        id: 8,
        Date: "9/25/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 90,
        "Static lunge": 45,
        "Dumbbell row": 70,
        "Barbell press": 70,
        Running: 8,
      },
      {
        id: 7,
        Date: "9/19/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Squat: 80,
        "Static lunge": 40,
        "Dumbbell row": 70,
        "Barbell press": 70,
        Running: 8,
      },
      {
        id: 6,
        Date: "9/5/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Squat: 70,
        "Static lunge": 40,
        "Dumbbell row": 55,
        "Barbell press": 60,
        Running: 8,
      },
      {
        id: 5,
        Date: "8/29/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Squat: 65,
        "Static lunge": 40,
        "Dumbbell row": 50,
        "Barbell press": 60,
        Running: 7,
      },
      {
        id: 4,
        Date: "8/22/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Squat: 65,
        "Static lunge": 40,
        "Dumbbell row": 40,
        "Barbell press": 60,
        Running: 7,
      },
      {
        id: 3,
        Date: "8/14/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Squat: 65,
        "Static lunge": 40,
        "Dumbbell row": 40,
        "Barbell press": 60,
        Running: 7,
      },
      {
        id: 2,
        Date: "8/7/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Squat: 60,
        "Static lunge": 50,
        "Dumbbell row": 40,
        "Barbell press": 50,
        Running: 6,
      },
      {
        id: 1,
        Date: "7/27/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Squat: 50,
        "Static lunge": 0,
        "Dumbbell row": 30,
        "Barbell press": 40,
        Running: 5,
      },
    ],
  },
  {
    program: "Break-In Deadlift",
    data: [
      {
        id: 17,
        Date: "3/8/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 40,
        "Shoulder press": 45,
        Pulldowns: 60,
        Running: 7,
      },
      {
        id: 16,
        Date: "3/8/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 40,
        "Shoulder press": 45,
        Pulldowns: 60,
        Running: 7,
      },
      {
        id: 15,
        Date: "3/4/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 80,
        "Dynamic lunge": 40,
        "Shoulder press": 40,
        Pulldowns: 55,
        Running: 7,
      },
      {
        id: 14,
        Date: "2/6/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 100,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 50,
        Running: 5,
      },
      {
        id: 13,
        Date: "2/1/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 60,
        Running: 5,
      },
      {
        id: 12,
        Date: "1/26/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 50,
        "Shoulder press": 50,
        Pulldowns: 55,
        Running: 9,
      },
      {
        id: 11,
        Date: "1/19/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 50,
        "Shoulder press": 50,
        Pulldowns: 55,
        Running: 9,
      },
      {
        id: 10,
        Date: "1/15/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 50,
        "Shoulder press": 50,
        Pulldowns: 55,
        Running: 9,
      },
      {
        id: 9,
        Date: "1/10/2024",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 45,
        "Shoulder press": 45,
        Pulldowns: 55,
        Running: 9,
      },
      {
        id: 8,
        Date: "11/21/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 50,
        "Shoulder press": 45,
        Pulldowns: 65,
        Running: 9,
      },
      {
        id: 7,
        Date: "9/22/2023",
        Reps: "3x8",
        "Rest (sec)": 120,
        Deadlift: 90,
        "Dynamic lunge": 60,
        "Shoulder press": 45,
        Pulldowns: 65,
        Running: 8,
      },
      {
        id: 6,
        Date: "9/8/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Deadlift: 75,
        "Dynamic lunge": 40,
        "Shoulder press": 40,
        Pulldowns: 60,
        Running: 8,
      },
      {
        id: 5,
        Date: "8/31/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Deadlift: 70,
        "Dynamic lunge": 40,
        "Shoulder press": 40,
        Pulldowns: 55,
        Running: 8,
      },
      {
        id: 4,
        Date: "8/24/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Deadlift: 70,
        "Dynamic lunge": 40,
        "Shoulder press": 40,
        Pulldowns: 55,
        Running: 6,
      },
      {
        id: 3,
        Date: "8/16/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Deadlift: 70,
        "Dynamic lunge": 40,
        "Shoulder press": 40,
        Pulldowns: 55,
        Running: 6,
      },
      {
        id: 2,
        Date: "8/11/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Deadlift: 60,
        "Dynamic lunge": 40,
        "Shoulder press": 40,
        Pulldowns: 50,
        Running: 6,
      },
      {
        id: 1,
        Date: "7/31/2023",
        Reps: "2x15",
        "Rest (sec)": 60,
        Deadlift: 60,
        "Dynamic lunge": 40,
        "Shoulder press": 40,
        Pulldowns: 45,
        Running: 0,
      },
    ],
  },
];
